Fix bug where createrepo can't be installed because local repo is broken
Errors during downloading metadata for repository 'local-rpm':
  - Curl error (37): Couldn't read a file:// file for file:///tmp/rpms/repodata/repomd.xml [Couldn't open file /tmp/rpms/repodata/repomd.xml]
Error: Failed to download metadata for repo 'local-rpm': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
/create_local_yum_repo.sh: line 4: createrepo: command not found