Only return passwords that include letters.
Password decryption can fail if the database password is all numbers because ruby will read it as an integer instead of a string.

== Checking deployment status ==
rake aborted!
NoMethodError: undefined method `empty?' for 8783875645714351:Integer
.../gems/manageiq-password-1.2.0/lib/manageiq/password.rb:165:in `remove_erb'
.../gems/manageiq-password-1.2.0/lib/manageiq/password.rb:90:in `try_decrypt'
/var/www/miq/vmdb/lib/vmdb/settings_walker.rb:76:in `block in decrypt_passwords!'